chore: also echo init-console logs to console (#9995)
Emit logs of the `init-console` service not only to stdout (journal) but
also to `/dev/ttyS0` such that they're visible in the console output of
the VM.

We need this to debug why the test
`//rs/tests/consensus/subnet_recovery:sr_app_large_no_upgrade_with_chain_keys_test_colocate`
[flaked](https://dash.dm1-idx1.dfinity.network/invocation/a397dc69-4d1f-4dac-aaa6-814a08f5dc51?target=//rs/tests/consensus/subnet_recovery:sr_app_large_no_upgrade_with_chain_keys_test_colocate).
The reason the test failed was that the driver could not authenticate
the `admin` user via SSH with one of the unassigned nodes:

```
2026-04-23 04:38:44.554 INFO[uvms_logs_stream:StdOut] [uvm=colocated-test-driver] TEST_LOG: 2026-04-23 04:38:44.085 INFO[setup:StdErr] thread 'main' (17) panicked at rs/tests/consensus/utils/src/rw_message.rs:300:14:
2026-04-23 04:38:44.554 INFO[uvms_logs_stream:StdOut] [uvm=colocated-test-driver] TEST_LOG: 2026-04-23 04:38:44.085 INFO[setup:StdErr] Timeout while waiting for all unassigned nodes to be healthy: Func="get_ssh_session to 2602:fb2b:110:10:5075:16ff:fe38:eb0 [rs/tests/driver/src/driver/test_env_api.rs:1697]" timed out after 502.202196983s on attempt 98. Last error: Failed to get SSH session
2026-04-23 04:38:44.554 INFO[uvms_logs_stream:StdOut] [uvm=colocated-test-driver] TEST_LOG: 2026-04-23 04:38:44.085 INFO[setup:StdErr] 
2026-04-23 04:38:44.554 INFO[uvms_logs_stream:StdOut] [uvm=colocated-test-driver] TEST_LOG: 2026-04-23 04:38:44.085 INFO[setup:StdErr] Caused by:
2026-04-23 04:38:44.554 INFO[uvms_logs_stream:StdOut] [uvm=colocated-test-driver] TEST_LOG: 2026-04-23 04:38:44.085 INFO[setup:StdErr]     0: Failed to get SSH session
2026-04-23 04:38:44.554 INFO[uvms_logs_stream:StdOut] [uvm=colocated-test-driver] TEST_LOG: 2026-04-23 04:38:44.085 INFO[setup:StdErr]     1: [Session(-18)] Username/PublicKey combination invalid
```

Note the driver could successfully establish and authenticate SSH
sessions to all other nodes. What's notable about the failing node is
that it didn't log `GUESTOS BOOT SUCCESS` to its console and that it
didn't forward its journal logs to ElasticSearch. This leads to the
hypothesis that it might have failed to mount its CONFIG drive. To
determine if this is the case we extend the `init-config` service to log
its message additionally to the console.