fix: revert "feat: [DSM-103] Actual priority queue for long executions (#10013)" (#10030)
This reverts commit 988244621aeb0975989cb39b4ad71e2c920aa2ce because it
breaks the `//rs/tests/consensus:subnet_splitting_test_colocate` test:
```
2026-04-27 12:20:33.510 INFO[uvms_logs_stream:StdOut] [uvm=colocated-test-driver] TEST_LOG: 2026-04-27 12:20:33.310 INFO[subnet_splitting_test:StdErr] thread 'main' (126) panicked at rs/tests/consensus/subnet_splitting_test.rs:173:33:
2026-04-27 12:20:33.510 INFO[uvms_logs_stream:StdOut] [uvm=colocated-test-driver] TEST_LOG: 2026-04-27 12:20:33.310 INFO[subnet_splitting_test:StdErr] Execution of step SplitOutDestinationState failed: Validation failed: State hash after split b55a0fa013f5d9aa08c1cfc70d683e7b1dbdda7d0789d47ff705b044c45000d1 doesn't match the expected state hash 0295d8206a0b9b88b95291d1d8d31beb4a837794036882b097e38c740a917892
```