test(ckdoge): fix ckdoge test setup (#10082)
## Summary
- Mine a block during `Setup` so the dogecoin canister is guaranteed up
and running before tests start
- Improve `DogecoinSyncGuard` logging to show progress and target block
height

## Details

Fix flakyness in ckDOGE integration tests that is visible in #8885 and
#9985 but currently not on master
(`63f33dc741a0e5ab50891e3532f52fa027fb3ff1`). The reason is apparent
when looking at the ckDOGE minter logs. For example for
`should_estimate_withdrawal_fee`:

1. Failed run
    ```
    [init]: Initializing canister with args InitArgs {...}
    
[estimate_fee_per_vbyte]: failed to get median fee per vbyte: management
call 'dogecoin_get_fee_percentiles' failed: the management canister
rejected the call: call rejected: 5 - IC0503: Error from Canister
gordg-fyaaa-aaaan-aaadq-cai: Canister called `ic0.trap` with message:
'Panicked at 'Canister state is not fully synced.'
    
Minted 5000000000 ckTESTBTC for account tjrnw-kiafi corresponding to
utxo f3fb3723df1f2b1189438c7c2429a712b974ba6aba418f7ba096bcf4aacc3822:0
with value 50.0
    ```
2. Successful run
    ```
    [init]: Initializing canister with args InitArgs {...}
    
[estimate_fee_per_vbyte]: update median fee per vbyte to
FeeRate(1000000000) and fee-based minimum retrieve amount to 5000000000
with []
    
Minted 5000000000 ckTESTBTC for account tjrnw-kiafi corresponding to
utxo f3fb3723df1f2b1189438c7c2429a712b974ba6aba418f7ba096bcf4aacc3822:0
with value 50.0
    ```

That means that:

1. The task to refresh fee percentiles runs directly after canister
initialization.
2. In rare occurrences the dogecoin canister is not yet available (not
synced to tip), hence the error.

The fix consists in ensuring as part of the test `Setup` instantiation
that the dogecoin canister is ready _before_ installing the ckDOGE
minter.

This subsumes #10072.

Co-authored-by: Claude Opus 4.7 (1M context) <noreply@anthropic.com>